version: 2.1

workflows:
  path_to_live:
    jobs:
      - pandoc-build/push_to_s3:
          name: push_to_s3
orbs:
  aws-s3: circleci/aws-s3@1.0.11
  pandoc-build:
    commands:
      install_aws_cli:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
    executors:
      python:
        docker: [image: circleci/python]

    jobs:
      push_to_s3:
        executor: python
        steps:
          - attach_workspace:
                at: .
          - run:
              name: curl pandoc from github
              command: |
                curl -s https://api.github.com/repos/jgm/pandoc/releases/latest \
                | grep "browser_download_url.*tar.gz" \
                | cut -d : -f 2,3 \
                | tr -d \" \
                | wget -qi -
                ls -al

