version: 2.1

workflows:
  path_to_live:
    jobs:
      - pandoc-build/build_pandoc:
          name: build_pandoc
      - pandoc-build/push_to_s3:
          name: push_to_s3
          requires: [build_pandoc]
orbs:
  pandoc-build:
    commands:
      install_aws_cli:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
    executors:
      python:
        docker: [image: circleci/python]
      lamci:
        docker: [image: lambci/lambda-base-2:build]

    jobs:
      build_pandoc:
        executor: lamci
        steps:
          - checkout
          - setup_remote_docker:
              version: 18.06.0-ce
              docker_layer_caching: false
          - run:
              name: build pandoc
              no_output_timeout: 30m
              command: |
                yum install sudo --assumeyes
                sudo make all -f ./Makefile_Pandoc
          - persist_to_workspace:
              root: /
              paths:
                - opt/bin
      push_to_s3:
        executor: python
        steps:
          - run:
              name: zip binary
              command: |
                cd /opt/bin
                zip -r pandoc_binary.zip pandoc
                ls -al

